In [2]:
a = [1, 2, 3]
print(a + [4, 5])   # [1, 2, 3, 4, 5]

[1, 2, 3, 4, 5]


In [4]:
import numpy as np

b = np.array([1, 2, 3])
print(b + np.array([4, 5, 6]))   # [5 7 9]

[5 7 9]


In [2]:
import numpy as np

arr1=np.array([6,7,5,4,3,2,1])
arr2=arr1*5
arr3=arr1/10
print(type(arr1))   # <class 'numpy.ndarray'>
print(type(arr2))   # <class 'numpy.ndarray'>   
print(type(arr3))   # <class 'numpy.ndarray'>   

print(arr1)   # [6 7 5 4 3 2 1]
print(arr2)   # [30 35 25 20 15 10 5]
print(arr3)   # [0.6 0.7 0.5 0.4 0.3 0.2 0.1]



<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[6 7 5 4 3 2 1]
[30 35 25 20 15 10  5]
[0.6 0.7 0.5 0.4 0.3 0.2 0.1]
